// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: create_user.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, email, pword, full_name, user_hours, user_minutes, jwt_token)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, created_at, updated_at, email, pword, full_name, user_hours, user_minutes, jwt_token
`

type CreateUserParams struct {
	Email       string
	Pword       string
	FullName    string
	UserHours   int32
	UserMinutes int32
	JwtToken    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.Pword,
		arg.FullName,
		arg.UserHours,
		arg.UserMinutes,
		arg.JwtToken,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Pword,
		&i.FullName,
		&i.UserHours,
		&i.UserMinutes,
		&i.JwtToken,
	)
	return i, err
}
