// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get-preferences-by-email.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const showUserPreferencesByEmail = `-- name: ShowUserPreferencesByEmail :one
SELECT u.id, u.email, up.preferences
FROM users u
LEFT JOIN user_preferences up ON u.id = up.user_id
WHERE u.email = $1
`

type ShowUserPreferencesByEmailRow struct {
	ID          uuid.UUID
	Email       string
	Preferences pqtype.NullRawMessage
}

func (q *Queries) ShowUserPreferencesByEmail(ctx context.Context, email string) (ShowUserPreferencesByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, showUserPreferencesByEmail, email)
	var i ShowUserPreferencesByEmailRow
	err := row.Scan(&i.ID, &i.Email, &i.Preferences)
	return i, err
}
