// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_user_by_token.sql

package database

import (
	"context"
)

const getUserByToken = `-- name: GetUserByToken :one
SELECT id, created_at, updated_at, email, pword, full_name, user_hours, user_minutes, jwt_token FROM users
WHERE jwt_token = $1
`

func (q *Queries) GetUserByToken(ctx context.Context, jwtToken string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByToken, jwtToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Pword,
		&i.FullName,
		&i.UserHours,
		&i.UserMinutes,
		&i.JwtToken,
	)
	return i, err
}
