// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: save_user_token.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const saveUserToken = `-- name: SaveUserToken :exec
UPDATE users
SET jwt_token = $2
WHERE id = $1
`

type SaveUserTokenParams struct {
	ID       uuid.UUID
	JwtToken string
}

func (q *Queries) SaveUserToken(ctx context.Context, arg SaveUserTokenParams) error {
	_, err := q.db.ExecContext(ctx, saveUserToken, arg.ID, arg.JwtToken)
	return err
}
