// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: save_preferences.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const savePreferences = `-- name: SavePreferences :exec
INSERT INTO user_preferences (user_id, preferences, preference_variables)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE
SET preferences = EXCLUDED.preferences,
    preference_variables = EXCLUDED.preference_variables
`

type SavePreferencesParams struct {
	UserID              uuid.UUID
	Preferences         json.RawMessage
	PreferenceVariables json.RawMessage
}

func (q *Queries) SavePreferences(ctx context.Context, arg SavePreferencesParams) error {
	_, err := q.db.ExecContext(ctx, savePreferences, arg.UserID, arg.Preferences, arg.PreferenceVariables)
	return err
}
