// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: show_user_preferences.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const showUserPreferencesByEmail = `-- name: ShowUserPreferencesByEmail :many
SELECT u.id, u.email, up.preferences
FROM users u
LEFT JOIN user_preferences up ON u.id = up.user_id
`

type ShowUserPreferencesByEmailRow struct {
	ID          uuid.UUID
	Email       string
	Preferences pqtype.NullRawMessage
}

func (q *Queries) ShowUserPreferencesByEmail(ctx context.Context) ([]ShowUserPreferencesByEmailRow, error) {
	rows, err := q.db.QueryContext(ctx, showUserPreferencesByEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShowUserPreferencesByEmailRow
	for rows.Next() {
		var i ShowUserPreferencesByEmailRow
		if err := rows.Scan(&i.ID, &i.Email, &i.Preferences); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
