// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: show_user_preferences.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const showAllUserPreferences = `-- name: ShowAllUserPreferences :many
SELECT u.id, u.email, u.user_hours, u.user_minutes, up.preferences
FROM users u
LEFT JOIN user_preferences up ON u.id = up.user_id
`

type ShowAllUserPreferencesRow struct {
	ID          uuid.UUID
	Email       string
	UserHours   int32
	UserMinutes int32
	Preferences pqtype.NullRawMessage
}

func (q *Queries) ShowAllUserPreferences(ctx context.Context) ([]ShowAllUserPreferencesRow, error) {
	rows, err := q.db.QueryContext(ctx, showAllUserPreferences)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShowAllUserPreferencesRow
	for rows.Next() {
		var i ShowAllUserPreferencesRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.UserHours,
			&i.UserMinutes,
			&i.Preferences,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
